"""cascade delete on quote to like

Revision ID: 1dc9f0d182f0
Revises: 943172f6b45b
Create Date: 2020-08-01 21:33:55.641133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc9f0d182f0'
down_revision = '943172f6b45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('like_quote_id_fkey', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'quote', ['quote_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_quote_id_fkey', 'like', 'quote', ['quote_id'], ['id'])
    # ### end Alembic commands ###
