"""sqlalchemy_searchable integration

Revision ID: 2f129a14c9a1
Revises: f3a6c7c3764f
Create Date: 2020-07-01 20:45:44.763637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_searchable import sync_trigger
from sqlalchemy_utils.types import TSVectorType

# revision identifiers, used by Alembic.
revision = '2f129a14c9a1'
down_revision = 'f3a6c7c3764f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('search_vector', TSVectorType(), nullable=True))
    op.create_index('ix_quote_search_vector', 'quote', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###

    sync_trigger(op.get_bind(), 'quote', 'search_vector', ['quotation', 'author'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quote_search_vector', table_name='quote')
    op.drop_column('quote', 'search_vector')
    # ### end Alembic commands ###
