"""added slug column in quote table

Revision ID: 4db34dfb846f
Revises: 8b2969f9ea14
Create Date: 2020-08-03 20:49:23.295011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db34dfb846f'
down_revision = '8b2969f9ea14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('slug', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'slug')
    # ### end Alembic commands ###
