"""Added name and picture_url columns in user table

Revision ID: 5e8ab368aba6
Revises: d682ec09d982
Create Date: 2020-07-19 18:57:50.253886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8ab368aba6'
down_revision = 'd682ec09d982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('picture_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture_url')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
