"""added unique constraint to author and quotation columns

Revision ID: 7fcbcd87b530
Revises: 2f129a14c9a1
Create Date: 2020-07-05 11:10:09.989476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcbcd87b530'
down_revision = '2f129a14c9a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'quote', ['author', 'quotation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quote', type_='unique')
    # ### end Alembic commands ###
