"""added created_at in like table

Revision ID: 943172f6b45b
Revises: 4a3fb4478471
Create Date: 2020-08-01 19:05:25.407821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943172f6b45b'
down_revision = '4a3fb4478471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('like', 'created_at')
    # ### end Alembic commands ###
