"""empty message

Revision ID: 9a2763fc8669
Revises: f38abacecd61
Create Date: 2020-02-29 13:35:00.513411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2763fc8669'
down_revision = 'f38abacecd61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uc_like', 'like', ['user_id', 'quote_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_like', 'like', type_='unique')
    # ### end Alembic commands ###
