"""Added is_published column to quote table

Revision ID: b064ba47fade
Revises: 7fcbcd87b530
Create Date: 2020-07-14 21:19:47.276587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b064ba47fade'
down_revision = '7fcbcd87b530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_quote_is_published'), 'quote', ['is_published'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_is_published'), table_name='quote')
    op.drop_column('quote', 'is_published')
    # ### end Alembic commands ###
