"""Added one to many relationship in user to quote table

Revision ID: d682ec09d982
Revises: b064ba47fade
Create Date: 2020-07-19 15:55:06.129302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd682ec09d982'
down_revision = 'b064ba47fade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('contributor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quote', 'user', ['contributor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quote', type_='foreignkey')
    op.drop_column('quote', 'contributor_id')
    # ### end Alembic commands ###
