"""empty message

Revision ID: f38abacecd61
Revises: d3347cf91982
Create Date: 2020-02-23 17:22:55.632287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38abacecd61'
down_revision = 'd3347cf91982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('like', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('like', 'updated_at')
    op.drop_column('like', 'created_at')
    # ### end Alembic commands ###
