"""initial migration

Revision ID: f9f0cf21d05c
Revises: 
Create Date: 2020-07-31 12:27:36.362988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_searchable import sync_trigger
from sqlalchemy_utils.types import TSVectorType

# revision identifiers, used by Alembic.
revision = 'f9f0cf21d05c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_user_id', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firebase_user_id')
    )
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('quotation', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('search_vector', TSVectorType(), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['quote_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quote_search_vector', 'quote', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('like',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'quote_id')
    )
    # ### end Alembic commands ###

    sync_trigger(op.get_bind(), 'quote', 'search_vector', ['quotation', 'author'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    op.drop_index('ix_quote_search_vector', table_name='quote')
    op.drop_table('quote')
    op.drop_table('user')
    op.drop_table('quote_type')
    # ### end Alembic commands ###
